export { default as About } from './About'
export { default as Footer } from './Footer'
export { default as Hero } from './Hero'
export { default as Location } from './Location'
export { default as Navbar } from './Navbar'
export { default as Payments } from './Payments'
export { default as Services } from './Services'
export { default as WhatsApp } from './WhatsApp'